version: '3.9'

services:
  # MinIO service
  minio:
    image: quay.io/minio/minio
    container_name: minio_container
    ports:
     - "9000:9000" # MinIO API Port
     - "9001:9001" # MinIO Console Port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data  # Persistent data storage for MinIO
    command: server /data --console-address ":9001"
    networks:
      - flask-network

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_SESSION_COOKIE_LIFETIME: "3600"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  postgres_data:
    name: flask_postgres_data
  pgadmin_data:
    name: flask_pgadmin_data
  minio_data:
    name: flask_minio_data  # Volume for MinIO data storage
